version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imcformedit
    image: yknam/imcformedit
    volumes:
      - ./src:/app/src
    ports:
      - "3080:80"
